# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Pipeline

on:
  pull_request:
    branches: [ "main", "develop" ]
  push:
    branches: [ "main" ]


jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v3


        
    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Instalar dependencias (backend)
      run: cd backend && npm install

    - name: Lint del código
      run: cd backend && npm run lint

    - name: Ejecutar pruebas con coverage
      run: cd backend && npm test -- --coverage

    - name: Instalar dependencias (frontend)
      run: cd frontend && npm install

    - name: Build del frontend
      run: cd frontend && npm run build
